USE demo;

# Cleanup

DROP TABLE IF EXISTS PETS;
DROP TABLE IF EXISTS OWNERS;

-- Create a pet table
CREATE TABLE PETS (
  NAME VARCHAR(20) NOT NULL, 
  OWNER VARCHAR(20),
  SPECIES VARCHAR(20),
  SEX CHAR(1),
  BIRTH DATE,
  DEATH DATE,
  PRIMARY KEY(NAME)
);


# Create a second table
CREATE TABLE OWNERS (
  NAME VARCHAR(20) NOT NULL, 
  EMAIL VARCHAR(100),
  PRIMARY KEY(NAME)
);

